---
title: Promise
date: 2020-08-11 19:45:43
permalink: /pages/6c13bd/
categories: 
  - JavaScript
  - ES6
tags: 
  - 
---

// Promise对象

//   含义

​    // 是异步编程的一种解决方案，比传统的回调函数和事件更合理和更强大

​    // 是一个容器，里面保存着某个未来才会结束的事件（异步操作）的结果

​    // 是一个对象，从它可以获取异步操作的消息

​    // 有三种状态：Pending（进行中）、Resolved（已完成，又称Fulfilled）和Rejected（已失败）

​    // 只有两种可能：从Pending变为Resolved和从Pending变为Rejected

​    // Promise新建后就会立即执行



//   基本用法

​    var promise = new Promise(function (resolve, reject) {

​        // ... some code

​        if (/* 异步操作成功 */true){

​            resolve(value);

​        } else {

​            reject(error);

​        }

​    });

​    //   Promise对象是一个构造函数

​    //   resolve函数将Promise对象的状态从Pending变为Resolved

​    //   reject函数将Promise对象的状态从Pending变为Rejected

​    //   它们的参数value和error会被传递给回调函数

​    promise.then(function (value) {

​        // success 

​    }, function (error) {

​            // failure 

​        });

​    //   用then方法分别指定Resolved状态和Reject状态的回调函数

​    //   第一个回调函数是Promise对象的状态变为Resolved时调用

​    //   第二个回调函数是Promise对象的状态变为Reject时调用(可选)

​    function timeout(ms) {

​        return new Promise((resolve, reject) => {

​            setTimeout(resolve, ms, 'done');

​        });

​    }

​    timeout(100).then((value) => {

​        console.log(value);

​    });

​    //   一段时间以后才会发生的结果

​    let promise = new Promise(function (resolve, reject) {

​        console.log('Promise'); resolve();

​    });

​    promise.then(function () {

​        console.log('Resolved.');

​    });

​    console.log('Hi!');

​    // Promise 

​    // Hi! 

​    // Resolved

​    //   Promise新建后就会立即执行,首先输出的是“Promise”

​    //   then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行

​    function loadImageAsync(url) {

​        return new Promise(function (resolve, reject) {

​            var image = new Image();

​            image.onload = function () {

​                resolve(image);

​            };

​            image.onerror = function () {

​                reject(new Error('Could not load image at ' + url));

​            };

​            image.src = url;

​        });

​    }

​    //   异步加载图片

​    var getJSON = function (url) {

​        var promise = new Promise(function (resolve, reject) {

​            var client = new XMLHttpRequest();

​            client.open("GET", url);

​            client.onreadystatechange = handler;

​            client.responseType = "json";

​            client.setRequestHeader("Accept", "application/json");

​            client.send(); function handler() {

​                if (this.readyState !== 4) { return; }

​                if (this.status === 200) {

​                    resolve(this.response);

​                } else {

​                    reject(new Error(this.statusText));

​                }

​            };

​        });

​        return promise;

​    };

​    getJSON("/posts.json").then(function (json) {

​        console.log('Contents: ' + json);

​    }, function (error) {

​        console.error('出错了', error);

​    });

​    //   Ajax操作

​    //   getJSON是对XMLHttpRequest对象的封装， 用于发出一个针对JSON数据的HTTP请求， 并且返回一个Promise对象

​    var p1 = new Promise(function (resolve, reject) {

​        // ... 

​    });

​    var p2 = new Promise(function (resolve, reject) {

​        // ...   

​        resolve(p1);

​    })

​    //   一个异步操作的结果是返回另一个异步操作

​    //   p1的状态决定了p2的状态

​    var p1 = new Promise(function (resolve, reject) {

​        setTimeout(() => reject(new Error('fail')), 3000)

​    })

​    var p2 = new Promise(function (resolve, reject) {

​        setTimeout(() => resolve(p1), 1000)

​    })

​    p2.then(result => console.log(result))

​        .catch(error => console.log(error)) // Error: fail

​    //   p1在3秒之后变为rejected

​    //   p2的状态在1秒之后改变，resolve方法返回的是p1

​    //   又过了2秒，p1变为rejected，导致触发catch方法指定的回调函数



//   then()

​    getJSON("/posts.json").then(function (json) {

​        return json.post;

​    }).then(function (post) {

​            // ... 

​        });

​    //   then方法返回的是一个新的Promise实例

​    //   第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数

​    getJSON("/post/1.json").then(function (post) {

​        return getJSON(post.commentURL);

​    }).then(function funcA(comments) {

​        console.log("Resolved: ", comments);

​        }, function funcB(err) {

​            console.log("Rejected: ", err);

​        });

​    //   前一个回调函数，有可能返回的还是一个Promise对象

​    //   后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用

​    getJSON("/post/1.json").then(

​        post => getJSON(post.commentURL)

​    ).then(comments => console.log("Resolved: ", comments), err => console.log("Rejected: ", err));



//   catch()

​    getJSON("/posts.json").then(function (posts) {

​        // ... 

​    }).catch(function (error) {

​            // 处理 getJSON 和 前一个回调函数运行时发生的错误   

​            console.log('发生错误！', error);

​        });

​    //   是.then(null, rejection)的别名，用于指定发生错误时的回调函数

​    //   getJSON方法变为Rejected或then方法指定的回调函数错误都会被catch捕获

​    //   一般不要在then方法里面定义Reject状态的回调函数，总是使用catch方法

​    p.then((val) => console.log("fulfilled:", val))

​        .catch((err) => console.log("rejected:", err));

​    // 等同于 

​    p.then((val) => console.log("fulfilled:", val))

​        .then(null, (err) => console.log("rejected:", err));

​    var promise = new Promise(function (resolve, reject) {

​        throw new Error('test');

​    });

​    promise.catch(function (error) {

​        console.log(error);

​    }); // Error: test

​    //   promise抛出一个错误，就被catch方法指定的回调函数捕获

​    var promise = new Promise(function (resolve, reject) {

​        try { throw new Error('test'); }

​        catch (e) { reject(e); }

​    });

​    promise.catch(function (error) {

​        console.log(error);

​    });

​    var promise = new Promise(function (resolve, reject) {

​        reject(new Error('test'));

​    });

​    promise.catch(function (error) {

​        console.log(error);

​    });

​    var promise = new Promise(function (resolve, reject) {

​        resolve('ok'); throw new Error('test');

​    });

​    promise.then(function (value) {

​        console.log(value)

​    }).catch(function (error) {

​        console.log(error)

​    }); // ok

​    //   状态已经变成Resolved，再抛出错误是无效的

​    var someAsyncThing = function () {

​        return new Promise(function (resolve, reject) {

​            // 下面一行会报错，因为x没有声明     

​            resolve(x + 2);

​        });

​    };

​    someAsyncThing().catch(function (error) {

​        console.log('oh no', error);

​    }).then(function () {

​            console.log('carry on');

​        });

​    // oh no [ReferenceError: x is not defined]

​    // carry on

​    //   catch方法返回的还是一个Promise对象

​    Promise.resolve()

​        .catch(function (error) {

​            console.log('oh no', error);

​        }).then(function () {

​            console.log('carry on');

​        }); // carry on

​    //   没有报错，跳过了catch方法，直接执行后面的then方法

​    //   then方法里面报错，就与前面的catch无关了

​    var someAsyncThing = function () {

​        return new Promise(function (resolve, reject) {

​            // 下面一行会报错，因为x没有声明     

​            resolve(x + 2);

​        });

​    };

​    someAsyncThing().then(function () {

​        return someOtherAsyncThing();

​    }).catch(function (error) {

​        console.log('oh no', error);

​        // 下面一行会报错，因为y没有声明   

​        y + 2;

​        }).then(function () {

​            console.log('carry on');

​        });

​        // oh no [ReferenceError: x is not defined]

​    //   catch方法抛出一个错误，因为后面没有别的catch方法了， 导致这个错误不会被捕获，也不会传递到外层



//   Promise.all()

​    var p = Promise.all([p1, p2, p3]);

​    //   将多个Promise实例，包装成一个新的Promise实例

​    //   p1、p2、p3都是Promise对象的实例

​    //   如果不是就会先调用Promise.resolve方法转为Promise实例

​    //   状态

​    //     只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled

​    //     只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected

​    //     第一个被reject的实例的返回值，会传递给p的回调函数

​    // 生成一个Promise对象的数组 

​    var promises = [2, 3, 5, 7, 11, 13].map(function (id) {

​        return getJSON("/post/" + id + ".json");

​    });

​    Promise.all(promises).then(function (posts) {

​        // ... 

​    }).catch(function (reason) {

​        // ...

​    });

​    const databasePromise = connectDatabase();

​    const booksPromise = databaseProimse.then(findAllBooks);

​    const userPromise = databasePromise.then(getCurrentUser);

​    Promise.all([booksPromise, userPromise]).then(([books, user]) => pickTopRecommentations(books, user));

  

//   Promise.race()

​    var p = Promise.race([p1,p2,p3]);

​    //   将多个Promise实例，包装成一个新的Promise实例

​    //   有一个实例率先改变状态，p的状态就跟着改变

​    //   那个率先改变的Promise实例的返回值，就传递给p的回调函数

​    var p = Promise.race([

​        fetch('/resource-that-may-take-a-while'),

​        new Promise(function (resolve, reject) {

​            setTimeout(() => reject(new Error('request timeout')), 5000)

​        })

​    ])

​    p.then(response => console.log(response))

​    p.catch(error => console.log(error))

​    //   5秒之内fetch方法无法返回结果，变量p的状态就会变为rejected



//   Promise.resolve()

​    var jsPromise = Promise.resolve($.ajax('/whatever.json'));

​    //   将现有对象转为Promise对象

​    //   将jQuery生成的deferred对象，转为一个新的Promise对象

​    let thenable = {

​        then: function (resolve, reject) {

​            resolve(42);

​        }

​    };

​    let p1 = Promise.resolve(thenable);

​    p1.then(function (value) {

​        console.log(value);  // 42 

​    });

​    //   将这个对象转为Promise对象，然后就立即执行then方法

​    var p = Promise.resolve('Hello');

​    p.then(function (s) {

​        console.log(s)

​    }); // Hello



//   Promise.reject()

​    var p = Promise.reject('出错了');

​    // 等同于 

​    var p = new Promise((resolve, reject) => reject('出错了'))

​    p.then(null, function (s) {

​        console.log(s)

​    }); // 出错了

​    // 返回一个新的Promise实例，该实例的状态为rejected

​        

//   附加方法

​    // done()

​    asyncFunc()

​        .then(f1)

​        .catch(r1)

​        .then(f2)

​        .done();

​        // done方法，总是处于回调链的尾端，保证抛出任何可能出现的错误

​    // finally()

​    server.listen(0)

​        .then(function () {

​            // run test   

​        }).finally(server.stop);

​        // 不管Promise对象最后状态如何，都会执行的操作

​        // 接受一个普通的回调函数作为参数

​          

//   应用

​    // 加载图片

​    const preloadImage = function (path) {

​        return new Promise(function (resolve, reject) {

​            var image = new Image();

​            image.onload = resolve;

​            image.onerror = reject;

​            image.src = path;

​        });

​    };

​    // Generator函数

​    function getFoo() {

​        return new Promise(function (resolve, reject) {

​            resolve('foo');

​        });

​    }

​    var g = function* () {

​        try {

​            var foo = yield getFoo(); console.log(foo);

​        }

​        catch (e) {

​            console.log(e);

​        }

​    };

​    function run(generator) {

​        var it = generator();

​        function go(result) {

​            if (result.done) return result.value;

​            return result.value.then(function (value) {

​                return go(it.next(value));

​            }, function (error) {

​                return go(it.throw(error));

​            });

​        }

​        go(it.next());

​    }

​    run(g);

​        // 使用Generator函数管理流程，遇到异步操作的时候，通常返回一个Promise对象

​        // 函数run用来处理这个Promise对象，并调用下一个next方法